name: Echo Context

on:
  push:
    branches:
      - master

jobs:
  echoContext:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Echo context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"