name: Echo Context

on:
  push:
    branches:
      - master

jobs:
  echoContext:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Echo context
        env:
          GITHUB_COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$GITHUB_COMMITS"