name: Echo Context

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Echo context
        run: echo ${{ github }}