name: Echo Context

on:
  push:
    branches:
      - master

jobs:
  echoCommits:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Echo last commit
        env:
          GITHUB_LAST_COMMIT: ${{ toJson(github.event.head_commit) }}
        run: echo "$GITHUB_LAST_COMMIT"
      
