name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.03
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"